### ISSUE TITLE
move ensureAuthenticated function down to the bottom of the file

### ISSUE THREAD

**Issue by pietgeursen** [one-mile/server#27]
There's a nice convention to put helper functions down towards the bottom of the file and have the main important functions at the top.

**Comment by harrison-symes** [comment]
Done

**Comment by kfrn** [comment]
Breaks code. "ReferenceError: ensureAuthenticated is not defined"
FNs moved back ([ref](https://github.com/one-mile/server/commit/b91fbedaa3a6158bc4b30edce43e0887f42a706a))

**Comment by kfrn** [comment]
Now done
